tf_variables = {
    "release": "${RELEASE}",
    "elk_vpc": "${ELK_VPC}",
    "elk_region": "${ELK_REGION}",
    "aws_region": "${CUSTOMER_REGION}",
    "env": "${ENVIRONMENT_NAME}",
    "jenkins_env": "${JENKINS_ENV}",
    "spot_price": "${SPOT_PRICE}",
    "customer": "${CUSTOMER_NAME}",
    "enable_aws_config": "${ENABLE_AWS_CONFIG}",
    "enable_dd": "${ENABLE_DD}",
    "dd_id": "${DD_ID}",
    "dd_app": "${DD_APP}",
    "use_2az": "${USE_2AZ}",
    "env_account_id": "${ENVIRONMENT_AWS_ACCOUNT_ID}",
    "vpnowner_account_id": "${VPNOWNER_ACCOUNT_ID}",
    "vpnowner_aws_profile": "${VPNOWNER_AWS_PROFILE}",
    "sst_account_id": "${SST_ACCOUNT_ID}",
    "cv_version": "${CV_VERSION}",
    "internal_cidr_start1": "${CIDR_RANGE_START1}",
    "internal_cidr_start2": "${CIDR_RANGE_START2}",
    "ec2_instance_types": {
        "cv": "${CV_INSTANCE_TYPE}",
        "tomcat": "${TOMCAT_INSTANCE_TYPE}",
        "nginx": "${NGINX_INSTANCE_TYPE}",
        "bastion": "${BASTION_INSTANCE_TYPE}"
    },
    "db_instance_class": "${DB_INSTANCE_CLASS}",
    "db_engine": "${DB_ENGINE}",
    "db_engine_version": "${DB_ENGINE_VERSION}",
    "db_allocated_storage": "${DB_ALLOCATED_STORAGE}",
    "db_max_allocated_storage": "${DB_MAX_ALLOCATED_STORAGE}",
    "db_apply_immediately": "${DB_APPLY_IMMEDIATELY}",
    "db_multi_az": "${DB_MULTI_AZ}",
    "db_id": "${DB_ENGINE}-${CUSTOMER_NAME}-${ENVIRONMENT_NAME}",
    "db_snapshot_id": "${DB_SNAPSHOT_ID}",
    "db_backup_retention_period": "${DB_BACKUP_RETENTION_PERIOD}",
    "db_maintenance_window": "${DB_MAINTENANCE_WINDOW}",
    "db_backup_window": "${DB_BACKUP_WINDOW}",
    "db_snapshot_schedule": "${DB_SNAPSHOT_SCHEDULE}",
    "db_copy_tags_to_snapshot": "${DB_COPY_TAGS_TO_SNAPSHOT}",
    "rds_parameters": {
        "${DB_PARAMETERS}"
    },
    "db_enable_snapshot_cleanup": "${DB_ENABLE_SNAPSHOT_CLEANUP}",
    "db_snapshot_retention_weekdays": "${DB_SNAPSHOT_RETENTION_WEEKDAYS}",
    "db_snapshot_retention_weeks": "${DB_SNAPSHOT_RETENTION_WEEKS}",
    "db_snapshot_retention_months": "${DB_SNAPSHOT_RETENTION_MONTHS}",
    "db_snapshot_retention_years": "${DB_SNAPSHOT_RETENTION_YEARS}",
    "db_snapshot_cleanup_schedule": "${DB_SNAPSHOT_CLEANUP_SCHEDULE}",
    "enable_vpn_access": "false",
    "enable_del_protection": "true",
    "use_transit_gateway": "false",
    "aws_asn_side": "${AWS_ASN_SIDE}",
    "vpn_ecmp_support": "${VPN_ECMP_SUPPORT}",
    "disable_oracle_ssl": "${DISABLE_ORACLE_SSL}",
    "disable_os_command": "true",
    "source_cidr_blocks_allowed": [
        "${CIDR_BLOCKS_ALLOWED}"
    ],
    "source_vpces_allowed": [],
    "vpn_connections": [],
    "customer_domain": "${CUSTOMER_DOMAIN}",
    "axcloud_domain": "${AXCLOUD_DOMAIN}",
    "infra_domains": "${INFRA_DOMAINS}",
    "service_type": "${SERVICE_TYPE}",
    "saas_customer": "${SAAS_CUSTOMER}",
    "saas_env": "${SAAS_ENV}",
    "r_package_mapper": "${R_PACKAGE_MAPPER}",
    "r_package_install_list": "${R_PACKAGE_LIST}",
    "customer_timezone" : "${CUSTOMER_TIMEZONE}",
    "customer_adfs_identifier": "${CUSTOMER_ADFS_IDENTIFIER}",
    "customer_ldap_ip": "${CUSTOMER_LDAP_IP}",
    "customer_directory_name": "${CUSTOMER_DIRECTORY_NAME}",
    "switch_saml": "${SWITCH_SAML}",
    "logz_enable": "${LOGZ_ENABLE}",
    "cv_log_level": "INFO",
    "enable_outbound_transfer": "${ENABLE_OUTBOUND_TRANSFER}",
    "ebs_vol_size": {
        "cv_vol_size": "${CV_VOL_SIZE}",
        "cv_log_vol_size": "${CV_LOG_VOL_SIZE}",
        "tomcat_vol_size": "${TOMCAT_VOL_SIZE}",
        "tomcat_log_vol_size": "${TOMCAT_LOG_VOL_SIZE}"
    },
    "efs": {
        "efs_throughput_mode": "${EFS_THROUGHPUT_MODE}",
        "efs_provisioned_throughput": "${EFS_PROVISIONED_THROUGHPUT}"
    },
    "enable_redshift": "false",
    "redshift": {
         "cluster_node_type": "",
         "cluster_number_of_nodes": "",
         "wlm_json_config": ""
     },
    "enable_citrixservices": "false",
    "citrixservices_owner": {
        "citrixservices_account_id": "",
        "citrixservices_vpc_id": "false",
        "citrixservices_vpc_cidr_block": "",
        "citrixservices_sg_vda_id": "",
        "citrixservices_route_table_ids": []
    },
    "enable_worm_compliance": "${ENABLE_WORM_COMPLIANCE}",
    "dbsources": {
    },
    "blacklisted_cv_tag": "${BLACKLISTED_CV_TAG}",
    "override_whitelist_config": {
        "override_classes": "false",
        "override_services": "false",
        "whitelist_classes": "",
        "whitelist_services": ""
    },
    "data_lineage_config": {
        "enable_data_lineage": "false",
        "dl_version": "",
        "license_type": ""
    },
    "enable_aurora": "${ENABLE_AURORA}",
    "enable_rest": "${ENABLE_REST}",
    "aurora_db_engine" :"${AURORA_DB_ENGINE}",
    "aurora_db_engine_version": "${AURORA_DB_ENGINE_VERSION}",
    "aurora_db_instance_class": "${AURORA_DB_INSTANCE_CLASS}",
    "enable_occ_file_share": "${ENABLE_OCC_FILE_SHARE}",
    "occ_env_tag": "${OCC_ENV_TAG}",
    "aws_managed_directory": "${AWS_MANAGED_DIRECTORY}",
    "enable_workspaces": "${ENABLE_WORKSPACES}",
    "internal_sec_cidr_start1": "${SECONDARY_CIDR_START1}",
    "internal_sec_cidr_start2": "${SECONDARY_CIDR_START2}",
    "workspace_bundle_id": "${WORKSPACE_BUNDLE_ID}",
    "user_workspaces": [],
    "use_datascope_refinitiv": "${USE_DATASCOPE_REFINITIV}",
    "higher_environments": [],
    "lower_environments": [],
    "archive_audit": {
        "enable_archive_audit": "",
        "archive_audit_cron" : "",
        "archive_audit_project_name" : "",
        "archive_audit_branch_name" : "",
        "archive_audit_wf_name" : "",
        "archive_audit_var_projectname" : "",
        "archive_audit_var_branchname" : ""
    },
    "enable_oci_db": "${ENABLE_OCI_DB}",
    "vcn_cidr": "${VCN_CIDR}",
    "first_oci_dbsource_user": " ",
    "oci_mtu_size": " ",
    "spark": {},
    "webproxy": {},
    "enable_sftp_transfer": "${ENABLE_SFTP_TRANSFER}",
    "mft_app_region": "${MFT_APP_REGION}",
    "mvt": {},
    "enable_byok": "${ENABLE_BYOK}",
    "enable_pgp": "${ENABLE_PGP}",
    "enable_env_health_check": "false",
    "map_tagging_config": {
        "map_tag_key": "map-migrated-na",
        "map_tag_value": "not applicable resource"
    }
}
